### ISSUE TITLE
Rpath detection incompatible with linked Frameworks

### ISSUE THREAD

**Issue by PatTheMav** [SCG82/macdylibbundler#5]
While rewriting OBS' build scripts I've chosen to build certain library dependencies as Frameworks (to keep associated resources cleanly bundled). Cmake dutifully links the main executable to the dynamic libraries contained within the Frameworks and sets the binary's `rpath` to the location of the frameworks within the build tree.

When `install`ing the targets, cmake changes the main executable's `rpath`s to common values (if defined). It will also correctly "install" the linked frameworks to the "Frameworks" subfolder.

In this scenario the main executable will be linked to the framework like this:

```
build/rundir/EXECUTABLE.app/Contents/MacOS/EXECUTABLE:
	@rpath/LIBRARY.framework/Versions/A/LIBRARY (compatibility version 0.0.0, current version 0.0.0)
```

The app will stumble on this entry as in `Utils.cpp` the search path is truncated to the token after the last forward slash in the path:

https://github.com/SCG82/macdylibbundler/blob/1e42b51a3b4ac04a169aa778944d58ad43351ce8/src/Utils.cpp#L417

I guess the idea was to remove the `@rpath/` token, but in this example it's removing the entire framework path and the dependency cannot be found (even though it would find it if the full path had been kept).

**Comment by SCG82** [comment]
@PatTheMav My apologies for not seeing this until now. Please let me know if this works for the aforementioned scenario.
